### ISSUE TITLE
Tạo product backlog

### ISSUE THREAD

**Issue by hieucnm** [nmcntt2-cntn2016/project1-DoTa#2]
#Idea1: App tìm đường đi tối ưu cho shipper

**Comment by hieucnm** [comment]
Về ý tưởng này, làm gì, làm cho ai, tại sao làm thì mình biết hết rồi. Vấn đề ở chỗ, cái này đã được google thực hiện hồi tháng 10/2016 rồi :(  Và dưới đây là link:

http://vnreview.vn/tin-tuc-khoa-hoc-cong-nghe/-/view_content/content/2034150/lam-sao-google-theo-doi-duoc-tinh-trang-giao-thong-diem-ket-xe

**Comment by htn274** [comment]
# IDEA 1: TÌM ĐƯỜNG ĐI TỐI ƯU (GotYourWay)
## Đặt vấn đề: 
Thường thì người ta sẽ tìm đường đi ngắn nhất từ 1 nơi này đến một nơi khác. Vấn đề đặt ra là nếu có một list các danh cần đi thì sao? Bài toán đặt ra là cho một danh sách các điểm cần đến, sắp xếp lộ trình sao cho thời gian ngắn nhất.
## Các chức năng cần có: 

- Cho phép add list danh sách đường đi

- Cập nhật tình hình giao thông: cái này có thể chỉ trên tổng quan thôi, ví dụ như là mình sẽ phân theo từng khung giờ trong ngày, thì những tuyến đường nào hay kẹt xe chẳng hạn. Còn việc tai nạn giao thông, sự cố tắc đường bất chợt thì chưa xét đến.

- Trả kết quả là đường đi cần phải đi

**P.s: Cái này theo quan điểm của mình thì thấy là nó nghiên về nghiên cứu thuật toán hơn :)) Sau khi khảo sát ý kiến mấy anh khóa trên, ý tưởng này phù hợp với đồ án 2 =]] nhưng chưa biết thế nào. Mình cứ hỏi ý kiến thầy đã :"> **

**Comment by hieucnm** [comment]
Nữ cho a hỏi xíu, tại vì a chưa rĩ lắm ^^.

Tức là bây giờ a có 1 list những nơi cần đến, thì bình thường a sẽ thực hiện những bước gì để tìm được đường đi tối ưu nhất ?
Và cái app mà mình sẽ làm sẽ cải thiện được những bước nào trong các bước đó ? ^^

**Comment by hieucnm** [comment]
Chưa rõ, ko phải "rĩ" :v

**Comment by htn274** [comment]
# IDEA 2: VÍ TIỀN THÔNG MINH (KeepYourMoney) 
## Đặt vấn đề:
Việc quản lý chi tiêu cho bản thân với mỗi người thật sự rất khó khăn. Bạn phải khổ sở ghi chép lại chi tiêu hàng ngày của mình, vấn đề là sau 1 buổi làm việc mệt nhọc, bạn còn phải vắt óc suy nghĩ mình đang tiêu bao nhiêu tiền cho hôm nay? Hay là việc bạn cứ tiêu tiền xả ga để rồi cuối tháng gặm gùi nhịn đói hay ăn mì tôm. 
## Ý tưởng:
Tạo ra một chiếc ví tiền thông minh, giúp kiểm soát chi tiêu của chủ nhân 
## Các chức năng cần có:

- Scan tờ tiền là bao nhiêu, để cập nhật số tiền hiện có trong ví. Có một số vấn đề đặt ra là tiền bị rách thì sao, tiền polyme mà đã cũ thì sao? Chưa giải quyết được =]] 

- Cho phép chủ nhân thiết lập số tiền dùng định kỳ hàng tháng 

- Thông báo khi số tiền vượt quá mức đã thiết lập

- Biểu đồ chi tiêu giữa hàng tuần hoặc tháng. Để người dùng có thể nhìn lại việc chi tiêu của bản thân

- Định vị khi ví tiền bị mất. À chỗ này hơi rắc rối :)) Tức là ví mình cũng như ví bình thường, kiểu như mất ví thì người ta có thể lấy hết tiền trong ví rồi vứt ví đi. Nên cần suy xét lại chức năng này có thật sự cần thiết không? 
## Một số vấn đề chưa suy nghĩ được:

- Máy sẽ chạy bằng gì? Pin à? Vậy thì phải sạc pin??? 

- Giả sử ví tiền chạy bằng pin, như vậy kích cỡ của nó sẽ như thế nào? Có thể bỏ túi vừa không? Có tiện lợi hay không? 

- Cần phải xét về mặt thời trang đối với người dùng là phụ nữ

**Comment by F-Princess** [comment]
cmt thử xem tên mình là gì @@

**Comment by paquoc** [comment]
@MinhHieu1512157 : A Hiếu ơi, e thấy Google chỉ thông báo tình trạng giao thông thôi, còn mình hơn nó ở chỗ là mình sử dụng dữ liệu đó kết hợp với bài toán tìm đường ngắn nhất để đưa ra đường đi tối ưu nhất. Theo em hình dùng thì người dùng sẽ nhập danh sách địa điểm, app sẽ làm phần còn lại.

@htn274 : Hồi chiều Quốc cũng có nghĩ về cái ví tiền thông minh, nghe tính năng thì hay đó, nhưng để có thể ứng dụng thực tiễn được thì chắc phải chờ những công nghệ trong tương lai, chứ dùng mấy thứ hiện tại chắc cái ví của mình không nhỏ gọn được. :'( Hoặc là mình phải cắt giảm chức năng lại.

**Comment by paquoc** [comment]
## **Tên đề tài: Ví tiền thông minh bảo mật và quản lí chi tiêu**

### Product Backlog
- Nhận diện vân tay để mở khóa
- Mà hình hiển thị số tiền hiện có
- Theo dõi tiền vào và ra (quét tờ tiền)
- Báo động khi bị trộm cắp
- Bluetooth với smartphone
- GPS báo vị trí khi bị mất
- Hệ thống quét mã vạch để ghi nhận món hàng được mua
- Đặt mức giới hạn tiêu dùng, cảnh báo khi sắp hết tiền

### Tại sao làm:
- Xuất phát từ trình trạng muốn quản lý thu chi nhưng không có thời gian ghi chép và không nhớ những khoản thu chi trong ngày, ứng dụng tạo ra để đáp ứng nhu cầu quản lý chi tiêu 1 cách tự động
- Tăng cường bảo mật cho ví tiền

### Đối tượng hướng đến
- Những người trung lưu, không sử dụng thanh toán bằng thẻ
- Những người có nhu cầu quản lý chặt chẽ, ghi chép các khoản thu chi
Sẽ có 2 phiên bản:
- Phiên bản basic: chỉ có tính năng bảo mật
- Phiên bản mở rộng: vừa bảo mật vừa ghi chép chi tiêu

### Làm như thế nào là làm ntn?

## **Tên đề tài: Ứng dụng tìm đường đi tối ưu giữa nhiều địa điểm**
Làm: app mobile hoặc web app

### Product Backlog:
- Tìm địa điểm
- Tìm đường đi ngắn nhất
- Tìm đường đi tối ưu (tắt đường, khoảng cách, đèn đỏ, tránh cao tốc, tránh đường hẹp...)
- Cập nhật liên tục theo thời gian

### Vì sao làm:
Đối tượng hướng đến chính là những người giao hàng, và những người đi tới nhiều địa điểm trong ngày, cần tiết kiệm thời gian, những người

**Comment by VoThiMyNy** [comment]
[Ví tiền]
Ý tưởng ban đầu rất hay. Nhưng mà sao giờ mình làm nó hơi phức tạp. Một số vấn đề Ny nhận thấy:
1. Nếu làm như Quốc mô tả thì nó khá đắt và có cảm giác là một món đồ điện tử chuyên nghiệp, như smart phone, nếu làm vậy thì không phù hợp với tầm trung người dùng. So với một cái ví như vậy thì một cái thẻ để quẹt khi chi tiêu mà một chương trình (máy tình, điện thoại) kết nối đến tài khoản ngân hàng để lấy thông tin hóa đơn rồi làm các việc như thống kê, giới hạn chi tiêu (thông báo qua smart phone) sẽ tiện lợi hơn. Ví cũng không giải quyết được bài toán mà thẻ không giải quyết được là chi tiêu nhỏ lẻ với những mặt hàng không có mã vạch. 
2. Cái ví như mô tả thì bảo mật tốt hơn nhưng thật ra là đang tạo thêm một thứ để người dùng phải tự giữ (như tự giữ smart phone vậy). Có thể giá trị số tiền trong ví lại không bằng giá trị cái ví.
Theo Ny thì mình nên làm đơn giản hơn. Còn đơn giản như thế nào thì Ny vẫn đang cân nhắc.

**Comment by hieucnm** [comment]
#Về ví tiền:
   - Anh cũng thấy như Ny nói đó. Ví của mình có vẻ hơi đa năng :v nên nếu hướng đến tầng lớp trunh lưu thì phải giảm bớt chức năng lại. Chỉ cần 1 ưu điểm duy nhất so với ví tiền bình thường và thẻ, đó là cảnh báo chi tiêu quá mức, là đủ để người dùng chọn rồi. Những chức năng khác là mình mở rộng thêm thôi.
     $$$ Product Backlog là danh sách những việc sẽ làm. Và những việc mình cần làm là xây dựng một website hướng dẫn người khác sử dụng sản phẩm của mình, không phải nêu các bước làm ra sản phẩm hay các chức năng của sản phẩm. Mọi người có chút nhầm rồi :v

#VềShipper: okay anh đã hiểu ý của mấy bạn. Cơ mà anh đang nghĩ thêm tính năng gì đó, chứ chỉ có việc kết hợp giữa đường đi ngắn nhất với tình hình giao thông thôi thì còn hạn chế quá. Ví dụ đang đi mà quên đường thì lại phải bật điện thoại lên xem lại, hay là thêm tính năng tính lượng xăng cần thiết cho toàn bộ chuyến đi, vân vân và mây mây :v

**Comment by hieucnm** [comment]
## Product Backlog
   A vừa xem lại nội dung đồ án. Product backlog và website là riêng, không phải product backlog nêu các bước làm website như anh nói hôm qua :3 Nên anh mới là người hiểu sai, không phải các bạn nhé :3 I am sorry :3 kakaka
